### ISSUE TITLE
Add GPT-bs benchmark

### ISSUE THREAD

**Issue by uditagarwal97** [DependableSystemsLab/LLTFI#42]
Add this NLP benchmark:
[https://github.com/onnx/models/tree/main/text/machine_comprehension/gpt2-bs](https://github.com/onnx/models/tree/main/text/machine_comprehension/gpt2-bs)

**Comment by AnushreeBannadabhavi** [comment]
Got the below error while converting the onnx model to LLVM IR.

`root@8651918eb41b:/home/LLTFI_gpt/LLTFI/sample_programs/ml_sample_programs/nlp_models/gpt2-bs# onnx-mlir --EmitLLVMIR  --instrument-onnx-ops="ALL" --InstrumentBeforeAndAfterOp gpt2-lm-head-bs-12.onnx
onnx-mlir: /home/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:256: const T& llvm::ArrayRef<T>::operator[](size_t) const [with T = long int; size_t = long unsigned int]: Assertion `Index < Length && "Invalid index!"' failed.
Aborted (core dumped)`
