### ISSUE TITLE
Uninitialized pointer variable in GenLLFIIndexPass.cpp may lead to segfaults

### ISSUE THREAD

**Issue by Alessio-Netti** [DependableSystemsLab/LLTFI#44]
In the __runOnModuleMain()__ function in __llvm\_passes/core/GenLLFIIndexPass.cpp__, an __Instruction__ pointer variable is declared as follows:

https://github.com/DependableSystemsLab/LLTFI/blob/88458b91f1698b7e4820a6d227bc1f277e72067e/llvm_passes/core/GenLLFIIndexPass.cpp#L12

In some cases, the for loop that comes after may not be entered at all, and since __currinst__ is not explicitly initialized, the code attempts to dereference whatever random address it contains. This can be easily fixed by initializing __currinst__ as follows:

```
Instruction *currinst = NULL;
```

This issue was encountered when attempting to run the __genllfiindex__ pass from the clang 15.0 frontend, while compiling the QMCPack v3.12.0 application.

**Comment by uditagarwal97** [comment]
Thanks for bringing this up, Alessio. 
Fixed in: https://github.com/DependableSystemsLab/LLTFI/commit/cbe90b9666789827af65cf943d3834af82140d8b
