### ISSUE TITLE
Unmanaged NULL pointer return from itaniumDemangle() function

### ISSUE THREAD

**Issue by Alessio-Netti** [DependableSystemsLab/LLTFI#45]
The __demangleFuncName()__ function in __llvm\_passes/core/Utils.cpp__ uses the LLVM built-in __itaniumDemangle()__ function as follows:

https://github.com/DependableSystemsLab/LLTFI/blob/88458b91f1698b7e4820a6d227bc1f277e72067e/llvm_passes/core/Utils.cpp#L12

It appears that, in some edge cases, __itaniumDemangle()__ will fail internally, set the __status__ flag accordingly and then return a NULL pointer. This case is currently not handled in the LLTFI code, leading to crashes for some compilation jobs. One simple fix would be to check for the value of __test__ when declaring the __demangled__ string as follows:

```
std::string demangled = test!=nullptr ? test : func;
```

However, I'm not sure about the implications of this and more investigation may be needed. It may also be a good idea to check for the length of the __func__ string before running the `func[0] == '_' && func[1] == 'Z'` if check.

This issue was encountered when attempting to run the __genllfiindex__ and __faultinjection__ passes from the clang 15.0 frontend, while compiling the QMCPack v3.12.0 application.

**Comment by uditagarwal97** [comment]
Thanks for bringing this up, Alessio. 
Fixed in: https://github.com/DependableSystemsLab/LLTFI/commit/cbe90b9666789827af65cf943d3834af82140d8b
