### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by Mehdi-Amininasab** [DependableSystemsLab/LLTFI#67]
Hi dear Dr Karthik,
Thank you for considering my request for solving my problem during LLTFI installation. You know, I deal with some errors when I try to install LLTFI. I have followed Auto-Installer step by step and I met all dependencies. I would appreciate it if you guide me to solve this problem. Furthermore, I send you some pictures that I took during the installation process, which are attached to this issue.

my device properties:

CPU: Intel Corei3 
Hard Disk: SSD 256G
Memory: 12Gigbyte
OS: Ubuntu 20.04.6 LTS

Dependencies:

    64 Bit Machine (preferably with GPU for faster training of ML programs)
    64 bit Linux (Ubuntu 20.04) or OS X
    CMake (minimum v3.15)
    Python 3 and above
    Ninja >= 1.10.2
    Internet Connection

Usage:

    Copy the InstallLLTFI.py script to where you want to build the LLTFI. Run "python3 InstallLLTFI.py -h" to see all running options/guidelines
    Run "python3 InstallLLTFI.py"

![1](https://github.com/DependableSystemsLab/LLTFI/assets/35096297/1cf31c51-acfd-41c0-bbdb-76093e8f55c8)
![2](https://github.com/DependableSystemsLab/LLTFI/assets/35096297/d67fe8d9-a37a-4be8-8045-64cebcf8c6cd)
![3](https://github.com/DependableSystemsLab/LLTFI/assets/35096297/3e44de67-9ca3-4b1b-b959-02389118c97e)
![4](https://github.com/DependableSystemsLab/LLTFI/assets/35096297/d2932ab6-19d0-4047-820f-6bf895709401)

**Comment by uditagarwal97** [comment]
Hi @Mehdi-Amininasab,
Sorry for the delayed response. You you still facing these errors?
The first error is during Tensorflow installation and you can try installing Tensorflow (2.12.0) manually.
The second error (in the last image) is because the LLVM build got terminated due to a lack of RAM in your PC. Again, try install LLVM manually: you can get the commands to run from https://github.com/DependableSystemsLab/LLTFI/blob/master/installer/InstallLLTFI.py

**Comment by uditagarwal97** [comment]
Hi @Mehdi-Amininasab,

You can easily get the Time of Injection (Time required to inject a fault) by finding the time required to execute the 'injectFunc' function. (https://github.com/DependableSystemsLab/LLTFI/blob/master/runtime_lib/FaultInjectionLib.c#L231)
This would be the recurring cost of fault injection.

To find the instruction in which the fault is injected, you can refer to ```llfi/llfi_stats_output/<Name of fault injection file>.```

I did not understand what do you mean by "Fan-in Fan-Out injected block", can you please elaborate?
