### ISSUE TITLE
The test about test_suit failed

### ISSUE THREAD

**Issue by xuwaa** [DependableSystemsLab/LLTFI#68]
Hi author，
Hello author,
As for the project I built, I tested the "Running tests" in the /build file and found that most of the test results failed. Could you please remind me where the problem occurred?

check_injection.py:67: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  suite = yaml.load(f)
check_injection.py:16: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(inputyaml)
=============== Result ===============
./SoftwareFaults/BufferOverflow_API              FAIL: No ./llfi folder found!
./SoftwareFaults/BufferOverflowMalloc_Data               FAIL: No ./llfi folder found!
./SoftwareFaults/BufferOverflowMemmove_Data              FAIL: No ./llfi folder found!
./SoftwareFaults/BufferUnderflow_API             FAIL: No ./llfi folder found!
./SoftwareFaults/CPUHog_Res              FAIL: No ./llfi folder found!
./SoftwareFaults/DataCorruption_Data             FAIL: No ./llfi folder found!
./SoftwareFaults/Deadlock_Res            FAIL: No ./llfi folder found!
./SoftwareFaults/HighFrequentEvent_Timing                FAIL: No ./llfi folder found!
./SoftwareFaults/InappropriateClose_API                  FAIL: No ./llfi folder found!
./SoftwareFaults/IncorrectOutput_API             FAIL: No ./llfi folder found!
./SoftwareFaults/IncorrectOutput_Data            FAIL: No ./llfi folder found!
./SoftwareFaults/InvalidMessage_MPI              FAIL: No ./llfi folder found!
./SoftwareFaults/InvalidPointer_Res              FAIL: No ./llfi folder found!
./SoftwareFaults/InvalidSender_MPI               FAIL: No ./llfi folder found!
./SoftwareFaults/LowMemory_Res           FAIL: No ./llfi folder found!
./SoftwareFaults/MemoryExhaustion_Res            FAIL: No ./llfi folder found!
./SoftwareFaults/MemoryLeak_Res                  FAIL: No ./llfi folder found!
./SoftwareFaults/NoAck_MPI               FAIL: No ./llfi folder found!
./SoftwareFaults/NoClose_API             FAIL: No ./llfi folder found!
./SoftwareFaults/NoDrain_MPI             FAIL: No ./llfi folder found!
./SoftwareFaults/NoMessage_MPI           FAIL: No ./llfi folder found!
./SoftwareFaults/NoOpen_API              FAIL: No ./llfi folder found!
./SoftwareFaults/NoOutput_API            FAIL: No ./llfi folder found!
./SoftwareFaults/NoOutput_Data           FAIL: No ./llfi folder found!
./SoftwareFaults/PacketStorm_MPI                 FAIL: No ./llfi folder found!
./SoftwareFaults/RaceCondition_Timing            FAIL: No ./llfi folder found!
./SoftwareFaults/StalePointer_Res                FAIL: No ./llfi folder found!
./SoftwareFaults/ThreadKiller_Res                FAIL: No ./llfi folder found!
./SoftwareFaults/UnderAccumulator_Res            FAIL: No ./llfi folder found!
./SoftwareFaults/WrongAPI_API            FAIL: No ./llfi folder found!
./SoftwareFaults/WrongDestination_Data           FAIL: No ./llfi folder found!
./SoftwareFaults/WrongMode_API           FAIL: No ./llfi folder found!
./SoftwareFaults/WrongPointer_Data               FAIL: No ./llfi folder found!
./SoftwareFaults/WrongRetrievedAddress_IO                FAIL: No ./llfi folder found!
./SoftwareFaults/WrongRetrievedFormat_IO                 FAIL: No ./llfi folder found!
./SoftwareFaults/WrongSavedAddress_IO            FAIL: No ./llfi folder found!
./SoftwareFaults/WrongSavedFormat_IO             FAIL: No ./llfi folder found!
./SoftwareFaults/WrongSource_Data                FAIL: No ./llfi folder found!
./HardwareFaults/funcname                PASS
./HardwareFaults/insttype                PASS
./HardwareFaults/llfiindex               PASS
./HardwareFaults/random                  PASS
./HardwareFaults/tracing                 PASS
./HardwareFaults/multiplebits            PASS
./BatchMode/NoOpen_API_WrongMode_API_BufferUnderflow_API                 FAIL: No ./llfi folder found!
./BatchMode/SoftwareFailureAutoScan              Subdirectories for failure modes not found!

**Comment by uditagarwal97** [comment]
Hi @xuwaa,
We no longer support SoftwareFaults with LLTFI that's why you see "./SoftwareFaults/WrongSavedFormat_IO FAIL: No ./llfi folder found!" errors.
But, for HardwareFaults, the test suite passes correctly.

**Comment by xuwaa** [comment]
Hello,@uditagarwal97
I have seen your reply and thank you for your answer.
