### ISSUE TITLE
No rule to make target /LLTFI/test_suite/BatchMode

### ISSUE THREAD

**Issue by FoundIzalith** [DependableSystemsLab/LLTFI#69]
The current version of LLTFI is failing to build due to a CMake error:

`make[2]: *** No rule to make target '/home/user/LLTFI/test_suite/BatchMode', needed by 'test_suite/BatchMode'
.  Stop.`
`CMakeFiles/Makefile2:622: recipe for target 'test_suite/CMakeFiles/test_suite.dir/all' failed`

This error occurs when running the setup script. This affects both the manual installation and the Docker build. I'm attempting to build manually with the command `./setup -LLFI_BUILD_ROOT $(pwd)/build -LLVM_SRC_ROOT $(pwd)/../llvm-project -LLVM_DST_ROOT $(pwd)/../llvm-project/build`

![Screenshot_20230705_114736](https://github.com/DependableSystemsLab/LLTFI/assets/53011549/b9d6a66a-da81-432a-b59a-b9645c07da0f)

**Comment by uditagarwal97** [comment]
Hi @FoundIzalith,
I've fixed this. Try installing LLTFI now.

**Comment by FoundIzalith** [comment]
It builds successfully now, thank you
